name: sample
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload
        uses: actions/upload-artifact
        with:
          path: .
